apiVersion: v1
kind: Service
metadata:
  name: snykcon-2020-loadbalancer
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: snykcon-2020
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: snykcon-2020-deployment
spec:
  selector:
    matchLabels:
      app: snykcon-2020
  replicas: 2 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: snykcon-2020
    spec:
      containers:
        - name: snykcon-2002
          image: benlaplanche/snykcon-2020:latest
          ports:
            - containerPort: 80
